# Generated by Django 5.2.12 on 2026-03-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('video_url', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('uy', 'Uy'), ('kvartira', 'Kvartira'), ('ijara', 'Ijara')], db_index=True, default='uy', max_length=16)),
                ('views', models.PositiveIntegerField(default=0)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reel',
                'verbose_name_plural': 'Reels',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
