# Generated by Django 5.2.12 on 2026-03-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('type_label', models.CharField(max_length=64)),
                ('category_id', models.CharField(db_index=True, max_length=32)),
                ('vip', models.BooleanField(default=False)),
                ('rating', models.CharField(max_length=8)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('district', models.CharField(max_length=128)),
                ('region', models.CharField(max_length=128)),
                ('address_line', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=64)),
                ('price_label', models.CharField(default='/ oyiga', max_length=64)),
                ('images', models.JSONField(default=list)),
                ('more_gallery_count', models.PositiveSmallIntegerField(default=0)),
                ('beds', models.PositiveSmallIntegerField(default=0)),
                ('baths', models.PositiveSmallIntegerField(default=0)),
                ('area_m2', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('agent_name', models.CharField(max_length=128)),
                ('agent_avatar', models.URLField(max_length=500)),
                ('agent_phone', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "E'lon",
                'verbose_name_plural': "E'lonlar",
                'ordering': ['id'],
            },
        ),
    ]
