# Generated by Django 5.2.12 on 2026-03-29 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='images',
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text="Bir nechta rasm qo'shish uchun qatorlarni to'ldiring.", upload_to='listings/%Y/%m/')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text="Kichik raqam avval ko'rinadi (0, 1, 2, …).")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', related_query_name='photo', to='listings.property')),
            ],
            options={
                'verbose_name': "E'lon rasmi",
                'verbose_name_plural': "E'lon rasmlari",
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
