# Generated by Django 5.2.12 on 2026-03-29 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_property_views_reviews'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-is_pinned', '-helpful_count', '-created_at'], 'verbose_name': 'Sharh / baho', 'verbose_name_plural': 'Sharhlar va baholar'},
        ),
        migrations.AlterField(
            model_name='property',
            name='address_line',
            field=models.CharField(max_length=500, verbose_name='Manzil (qator)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='agent_avatar',
            field=models.URLField(max_length=500, verbose_name='Agent rasmi (havola)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='agent_name',
            field=models.CharField(max_length=128, verbose_name='Agent F.I.Sh.'),
        ),
        migrations.AlterField(
            model_name='property',
            name='agent_phone',
            field=models.CharField(max_length=32, verbose_name='Agent telefoni'),
        ),
        migrations.AlterField(
            model_name='property',
            name='area_m2',
            field=models.PositiveIntegerField(default=0, verbose_name='Maydon (m²)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='baths',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Sanuzel soni'),
        ),
        migrations.AlterField(
            model_name='property',
            name='beds',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Yotoqxona soni'),
        ),
        migrations.AlterField(
            model_name='property',
            name='category_id',
            field=models.CharField(db_index=True, help_text='Masalan: kvartira, hovli, uylar.', max_length=32, verbose_name='Kategoriya kodi'),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, verbose_name='Batafsil tavsif'),
        ),
        migrations.AlterField(
            model_name='property',
            name='district',
            field=models.CharField(max_length=128, verbose_name='Tuman / mahalla'),
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name="E'lon ID"),
        ),
        migrations.AlterField(
            model_name='property',
            name='more_gallery_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Galereyada qo'shimcha rasm soni (ko'rsatish)"),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.CharField(help_text='Masalan: $1 500 yoki kelishilgan.', max_length=64, verbose_name='Narx'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_label',
            field=models.CharField(default='/ oyiga', help_text='Masalan: / oyiga, / sotuv.', max_length=64, verbose_name='Narx izohi'),
        ),
        migrations.AlterField(
            model_name='property',
            name='region',
            field=models.CharField(max_length=128, verbose_name='Shahar / viloyat'),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type_label',
            field=models.CharField(help_text='Masalan: Kvartira, Hovli.', max_length=64, verbose_name="Mulk turi (ko'rinadigan matn)"),
        ),
        migrations.AlterField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name="Oxirgi o'zgarish"),
        ),
        migrations.AlterField(
            model_name='property',
            name='vip',
            field=models.BooleanField(default=False, verbose_name="VIP e'lon"),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqt'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(help_text="Bir nechta rasm uchun har bir qatorga alohida rasm tanlang. Pastdagi tugma orqali qator qo'shishingiz mumkin (cheksiz).", upload_to='listings/%Y/%m/', verbose_name='Rasm fayli'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', related_query_name='photo', to='listings.property', verbose_name="E'lon"),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='0 — birinchi rasm, keyingi raqamlar keyin chiqadi.', verbose_name='Tartib raqami'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='Profil rasmi')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi profili',
                'verbose_name_plural': 'Foydalanuvchi profillari',
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorites', to='listings.property', verbose_name="E'lon")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_favorites', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "Sevimli e'lon",
                'verbose_name_plural': "Sevimli e'lonlar",
                'constraints': [models.UniqueConstraint(fields=('user', 'listing'), name='user_favorite_listing_uniq')],
            },
        ),
    ]
