# Generated by Django 5.2.11 on 2026-03-31 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_property_lat_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='category_id',
            field=models.CharField(choices=[('uylar', 'Uylar'), ('ijara', 'Ijara'), ('hovli', 'Hovli'), ('kvartira', 'Kvartira'), ('dacha', 'Dacha'), ('mehmonxona', 'Mehmonxona'), ('quruq-yer', 'Quruq yer')], db_index=True, help_text="Ro'yxatdan tanlang: uylar, ijara, hovli, kvartira, dacha, mehmonxona, quruq-yer.", max_length=32, verbose_name='Kategoriya kodi'),
        ),
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Xarita (Leaflet/OSM) uchun. Masalan Toshkent: 41.31', null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Kenglik (xarita)'),
        ),
    ]
