# Generated by Django 5.2.11 on 2026-03-31 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_property_category_id_alter_property_latitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff', models.CharField(choices=[('simple', "Oddiy (50 000 so'm)"), ('vip', "VIP (250 000 so'm)")], default='simple', max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=12)),
                ('title', models.CharField(max_length=500)),
                ('type_label', models.CharField(max_length=64)),
                ('category_id', models.CharField(choices=[('uylar', 'Uylar'), ('ijara', 'Ijara'), ('hovli', 'Hovli'), ('kvartira', 'Kvartira'), ('dacha', 'Dacha'), ('mehmonxona', 'Mehmonxona'), ('quruq-yer', 'Quruq yer')], max_length=32)),
                ('audience', models.CharField(blank=True, default='', max_length=64)),
                ('district', models.CharField(max_length=128)),
                ('region', models.CharField(default='Toshkent shahri', max_length=128)),
                ('address_line', models.CharField(max_length=500)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('price', models.CharField(max_length=64)),
                ('price_label', models.CharField(default='/ oyiga', max_length=64)),
                ('beds', models.PositiveSmallIntegerField(default=0)),
                ('baths', models.PositiveSmallIntegerField(default=0)),
                ('area_m2', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('payment_card', models.CharField(default='8600 1234 5678 9012', max_length=64)),
                ('payment_proof', models.FileField(upload_to='payment-proofs/%Y/%m/')),
                ('admin_note', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "To'lovli e'lon arizasi",
                'verbose_name_plural': "To'lovli e'lon arizalari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingSubmissionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='submission-images/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listingsubmission')),
            ],
            options={
                'verbose_name': 'Ariza rasmi',
                'verbose_name_plural': 'Ariza rasmlari',
                'ordering': ['id'],
            },
        ),
    ]
