# Generated by Django 5.2.11 on 2026-03-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_listingsubmission_listingsubmissionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingsubmission',
            name='amenities',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='listingsubmission',
            name='building_floors',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingsubmission',
            name='extra_info',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='listingsubmission',
            name='floor_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingsubmission',
            name='phone1',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='listingsubmission',
            name='phone2',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='listingsubmission',
            name='phone3',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='listingsubmission',
            name='property_condition',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
